### ISSUE TITLE
rclone is available with restic-exporter?

### ISSUE THREAD

**Issue by damien-reyre** [ngosang/restic-exporter#18]
Hello,

I'm trying to implement rclone with your restic-exporter, but I get an error:

`restic-exporter-3  | 2023-06-14 15:27:00 ERROR    Unable to collect metrics from Restic. Exception: Error executing restic snapshot command: Fatal: unable to open repository at rclone:pcloud:OVH: exec: "rclone": executable file not found in $PATH  Exit code: 1`

![image](https://github.com/ngosang/restic-exporter/assets/117079206/758ec806-1541-4cb6-9a4b-c27563aeba24)

Here my docker-compose.yaml :

![image](https://github.com/ngosang/restic-exporter/assets/117079206/7250a126-ef03-4ce4-a03c-e783364d7734)

**Comment by damien-reyre** [comment]
@ngosang Could you confirm rclone is working with your restic-exporter?

Thanks

**Comment by koenvdheuvel** [comment]
I fixed this by mounting the rclone executable from my host inside the docker container.

While I'm not sure if this is best practice. It does allow the rclone version to be in sync with the version I'm running on my host machine.


```yaml
restic_exporter:
    image: ngosang/restic-exporter
    container_name: restic-exporter
    environment:
      TZ: Europe/Amsterdam
      RESTIC_REPO_URL: rclone:gd-backup:
      RESTIC_REPO_PASSWORD: 
      REFRESH_INTERVAL: 1800 # 30 min
    volumes:
      - /docker:/data:ro
      - /usr/bin/rclone:/usr/bin/rclone:ro
      - /mnt/config/rclone.conf:/root/.config/rclone/rclone.conf
    ports:
      - "8001:8001"
    restart: unless-stopped
  ```
